---
#  SonarQube Defaults

# Temporary packages for SonarQube install (removed after install)
sonar_temporary_packages:
  - unzip

# Packages required on the SonarQube server (persistent)
sonar_required_packages:
  - fontconfig
  - freetype

# Install requirements
sonar_max_map_count: 524288
sonar_file_max: 131072
sonar_limitnofile: 131072
sonar_limitnproc: 8192

# SonarQube version to install
sonar_version: 9.7.1.62043

# SonarQube URLs
sonar_source_url: "https://binaries.sonarsource.com"
sonar_archive: "sonarqube-{{ sonar_version }}.zip"
sonar_download_url: "{{ sonar_source_url }}/Distribution/sonarqube/{{ sonar_archive }}"

# SonarQube directorys
sonar_install_directory: /opt/sonarqube
sonar_base_dir: "{{ sonar_install_directory }}/sonarqube-{{ sonar_version }}"
sonar_daemon_dir: "{{ sonar_base_dir }}/bin/linux-x86-{{ ansible_userspace_bits }}"
sonar_conf_dir: "{{ sonar_base_dir }}/conf"
sonar_logs_dir: "/var/log/sonarqube"
sonar_data_dir: "{{ sonar_base_dir }}/data" # embedded database and search index
sonar_temp_dir: "{{ sonar_base_dir }}/temp"

# SonarQube user configuration
sonar_group: sonar
sonar_user: sonar

# TCP port for incoming HTTP connections. Default value is 9000.
sonar_web_port: 9000
