#!/bin/bash

BOLD=$(tput bold)
NORMAL=$(tput sgr0)

DARK_GREY='\033[1;30m'
NO_COLOUR='\033[0m'
RED='\033[0;31m'
YELLOW='\033[1;33m'

banner () {
    eval $(echo printf -- '"$1%0.s"' {1..$(tput cols)})
    printf "\n"
}

check_ansible_version () {
    local required_version="2.7.9"
    local version=$(ansible --version | head -n 1 | cut -d ' ' -f2)
    if [[ $version != $required_version ]]; then
        print_error "Incorrect version of Ansible: $version ($required_version required)"
        exit 1
    fi
}

check_proceed () {
    banner "-"
    printf "AWS Profile: ${BOLD}$AWS_PROFILE${NORMAL}\n"
    banner "-"

    read -p "Do you wish to proceed? (yes/no) " answer
    printf "\n"
    if [[ "$answer" != "yes" ]]; then
        echo "User elected not to proceed"
        exit 0
    fi
}

print_error () {
    printf "${RED}Error: ${NO_COLOUR}$1\n"
}

validate_profile () {
    if [[ -z "$AWS_PROFILE" ]]; then
        print_error "No AWS profile selected (${BOLD}AWS_PROFILE)${NORMAL}"
        exit 1
    fi

    local required_credentials=(
        region
        aws_access_key_id
        aws_secret_access_key
    )
    local missing_credentials=false

    for env_var in ${required_credentials[@]}; do
        value=$(aws configure get $env_var)
        if [[ -z $value ]]; then
            print_error "${env_var} credential missing from your AWS_PROFILE. You must re-configure your AWS_profile to proceed"
            missing_credentials=true
        fi
    done

    if [[ $missing_credentials == true ]]; then
        exit 1
    fi
}
