#!/bin/bash

ANSIBLE_VAULT_PASSWORD_FILE=~/.vault/code-analysis-ansible
PLAYBOOK_DIRECTORY=$(cd "$(dirname "$0")" && pwd)
SCRIPTS_DIRECTORY=$PLAYBOOK_DIRECTORY/scripts

find $PLAYBOOK_DIRECTORY -name "vault" -exec ansible-vault decrypt {} --vault-password-file "$ANSIBLE_VAULT_PASSWORD_FILE" \;
