---

# Check the system limits
- name: Check if vm.max_map_count is less than 524288
  shell: "sysctl vm.max_map_count | grep -Eo '[0-9]{1,}'"
  register: prereq_mmc
  failed_when: not prereq_mmc.stdout|int >= 524288
  changed_when: false

- name: Check if fs.file-max is less than 131072
  shell: "sysctl fs.file-max | grep -Eo '[0-9]{1,}'"
  register: prereq_fsmax
  failed_when: not prereq_fsmax.stdout|int >= 131072
  changed_when: false

# Check the user specific limits
- name: Check if user {{ sonar_user }} file descriptors less than 131072
  command: "ulimit -n 2> /dev/null"
  become: true
  become_method: su
  become_user: "{{ sonar_user }}"
  register: prereq_fd
  failed_when: not prereq_fd.stdout|int >= 131072
  changed_when: false

- name: Check if user {{ sonar_user }} threads less than 8192
  command: "su - {{ sonar_user }} --shell /bin/bash -c \"ulimit -u\" 2> /dev/null"
  register: prereq_td
  failed_when: not prereq_td.stdout|int >= 8192
  changed_when: false

# Check kernel has seccomp
- name: Check that seccomp is enabled
  shell: "grep {{ item }} /boot/config-$(uname -r)"
  changed_when: false
  with_items:
    - "CONFIG_HAVE_ARCH_SECCOMP_FILTER=y"
    - "CONFIG_SECCOMP_FILTER=y"
    - "CONFIG_SECCOMP=y"
