---

# Remove packages we used during the install
- name: Remove redundant packages
  ansible.builtin.package:
    name: "{{ item }}"
    state: absent
  with_items:
    - "{{ sonarqube_temporary_packages }}"

# Remove unnecessary pip packages
- name: Remove redundant pip package
  ansible.builtin.pip:
    name: boto3
    state: absent

# Remove temporary folder
- name: Remove the temporary folder
  ansible.builtin.file:
    path: "{{ tempfile.path }}"
    state: absent
  when: tempfile.path is defined
