---

# Install required packages
- name: Install temporary and required packages
  ansible.builtin.package:
    name: "{{ item }}"
    state: present
  with_items:
    - "{{ sonarqube_temporary_packages }}"
    - "{{ sonarqube_required_packages }}"

# Install Ansible S3 requirements
- name: Install boto3 python package
  ansible.builtin.pip:
    name: boto3
    state: present

# Config SonarQube user
- name: Create SonarQube system group
  ansible.builtin.group:
    name: "{{ sonarqube_group }}"
    system: true
    state: present

- name: Create SonarQube system user
  ansible.builtin.user:
    name: "{{ sonarqube_user }}"
    group: "{{ sonarqube_group }}"
    shell: "/sbin/nologin"
    comment: "SonarQube System user"
    system: true
    state: present

# Configure SonarQube prerequisites with system and user limits
- name: Update vm.sonar_max_map_count in sysctl
  ansible.posix.sysctl:
    name: vm.max_map_count
    value: "{{ sonarqube_max_map_count }}"
    sysctl_file: /etc/sysctl.d/99-sonarqube.conf

- name: Update fs.file-max in sysctl
  ansible.posix.sysctl:
    name: fs.file-max
    value: "{{ sonarqube_file_max }}"
    sysctl_file: /etc/sysctl.d/99-sonarqube.conf

- name: Update the user limits
  ansible.builtin.template:
    src: user.limits.j2
    dest: /etc/security/limits.d/99-sonarqube.conf
    owner: root
    group: root
    mode: "0644"

# Create SonarQube directories
- name: Create SonarQube directories
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    owner: "{{ sonarqube_user }}"
    group: "{{ sonarqube_group }}"
    mode: "u=rwx,g=rx,o="
  with_items:
    - "{{ sonarqube_install_directory }}"
    - "{{ sonarqube_data_dir }}"
    - "{{ sonarqube_logs_dir }}"
    - "{{ sonarqube_temp_dir }}"
    - "{{ sonarqube_management_dir }}"
