---

# Install required packages
- name: Install temporary and required packages
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - "{{ temporary_packages }}"
    - "{{ required_packages }}"

# Config SonarQube user
- name: Create SonarQube system group
  group:
    name: "{{ sonar_group }}"
    state: present

- name: Create SonarQube system user
  user:
    name: "{{ sonar_user }}"
    group: "{{ sonar_group }}"
    shell: "/sbin/nologin"
    comment: "SonarQube System user"
    createhome: no
    state: present

# Configure SonarQube prerequisites with system and user limits
- name: Add vm.max_map_count={{ max_map_count }} to sysctl
  sysctl:
    name: vm.max_map_count
    value: "{{ max_map_count }}"
    sysctl_file: /etc/sysctl.d/99-sonarqube.conf

- name: Add fs.file-max={{ file_max }} to sysctl
  sysctl:
    name: fs.file-max
    value: "{{ file_max }}"
    sysctl_file: /etc/sysctl.d/99-sonarqube.conf

- name: Update the user limits
  template:
    src: user.limits.j2
    dest: /etc/security/limits.d/99-sonarqube.conf
    owner: root
    group: root
    mode: 0644

# Create SonarQube directories
- name: Create SonarQube directories
  file:
    path: "{{ item }}"
    state: directory
    owner: "{{ sonar_user }}"
    group: "{{ sonar_group }}"
    mode: "u=rwx,g=rx,o="
  with_items:
    - "{{ sonar_install_directory }}"
    - "{{ sonar_data_dir }}"
    - "{{ sonar_logs_dir }}"
    - "{{ sonar_temp_dir }}"
