---
# Main - Install Java, Configure Linux and install Sonarqube

- name: Check JAVA is installed
  ansible.builtin.include_tasks: check_java.yml

- name: Configure Linux
  ansible.builtin.include_tasks: configure_linux.yml

- name: Setup SonarQube
  ansible.builtin.include_tasks: setup_sonarqube.yml

- name: Cleanup
  ansible.builtin.include_tasks: cleanup_install.yml
